import 'dart:convert';

import 'package:dart_style/dart_style.dart';

import 'errors.dart';
import 'schema.dart';

const String generatedNotice =
    '// GENERATED CODE - DO NOT MODIFY BY HAND.\n'
    '// Generated by tomgen from g.toml.\n';

/// Emits the phase-one Dart library consumed by the existing builder.
final class TomgenEmitter {
  TomgenEmitter()
    : _formatter = DartFormatter(
        languageVersion: DartFormatter.latestLanguageVersion,
      );

  final DartFormatter _formatter;

  String emit(
    TomgenSchema schema, {
    required String packageName,
    String? sourceDigest,
  }) {
    final target = schema.target;
    final model = target.model;
    final obfuscated = schema.fields
        .where((field) => field.obfuscated)
        .toList();
    final buffer = StringBuffer(generatedNotice)
      ..writeln()
      ..writeln("import 'package:tomg/tomg.dart';")
      ..writeln()
      ..writeln("part '${target.name}.g.dart';")
      ..writeln();

    for (final enumConfig in schema.enumDeclarations) {
      buffer.writeln(
        'enum ${enumConfig.name} { ${enumConfig.values.join(', ')} }',
      );
      buffer.writeln();
    }

    for (final nested in schema.models.where((item) => !item.isRoot)) {
      _emitModel(buffer, nested);
      buffer.writeln();
    }

    final source = target.sourceRelative.replaceAll('\\', '/');
    if (target.isExternal) {
      if (sourceDigest == null) {
        throw TomgenException(
          'External source for target "${target.name}" requires a digest.',
        );
      }
      buffer.writeln(
        '@TomgRegistry(${jsonEncode(source)}, key: ${jsonEncode(target.key)}, '
        'digest: ${jsonEncode(sourceDigest)})',
      );
    } else {
      buffer.writeln(
        "@TomgRegistry('asset:$packageName/$source', key: '${target.key}')",
      );
    }
    buffer.write('class $model');
    if (obfuscated.isNotEmpty) {
      buffer.write(' implements Obfuscated<${model}Deobf>');
    }
    buffer.writeln(' {');
    _emitModelBody(buffer, schema.rootModel);
    if (obfuscated.isNotEmpty) {
      buffer.writeln('  @override');
      buffer.writeln('  ${model}Deobf get deobf => ${model}Deobf(this);');
    }
    buffer.writeln('}');
    buffer.writeln();
    final alias = '${_lowerCamel(model)}Registry';
    final keyType = schema.keyField.type.dartType;
    buffer.writeln('const Map<$keyType, $model> $alias = \$$model;');

    try {
      return _formatter.format(buffer.toString(), uri: target.outputFile.uri);
    } on Object catch (error) {
      throw TomgenException(
        'Failed to format generated model for target "${target.name}": $error',
      );
    }
  }

  void _emitModel(StringBuffer buffer, TomgenModel model) {
    buffer.writeln('class ${model.name} {');
    _emitModelBody(buffer, model);
    buffer.writeln('}');
  }

  void _emitModelBody(StringBuffer buffer, TomgenModel model) {
    buffer.writeln('  const ${model.name}({');
    for (final field in model.fields) {
      buffer.write('    ');
      if (field.obfuscated) buffer.write('@Obfus() ');
      if (field.required) {
        buffer.write('required this.${field.name}');
      } else if (field.hasDefault) {
        buffer.write(
          'this.${field.name} = ${_literal(field.defaultValue, field.type)}',
        );
      } else {
        buffer.write('this.${field.name}');
      }
      buffer.writeln(',');
    }
    buffer.writeln('  });');
    buffer.writeln();
    for (final field in model.fields) {
      if (field.obfuscated) buffer.writeln('  @Obfus()');
      buffer.writeln('  final ${field.dartType} ${field.name};');
      buffer.writeln();
    }
  }

  String _literal(Object? value, TomgenType type) {
    if (type.isList) {
      final values = value as List;
      final itemShape = type.itemType!;
      final itemType = itemShape.dartType;
      return 'const <$itemType>[${values.map((item) => _literal(item, itemShape)).join(', ')}]';
    }
    if (type.enumConfig != null) {
      return '${type.enumConfig!.name}.$value';
    }
    if (type.scalar == TomgenScalarKind.doubleValue && value is int) {
      return '$value.0';
    }
    return switch (value) {
      String() => jsonEncode(value),
      double() when value.isFinite => value.toString(),
      double() => throw TomgenException('Non-finite defaults are unsupported.'),
      int() || bool() => value.toString(),
      _ => throw TomgenException('Unsupported generated default: $value'),
    };
  }

  String _lowerCamel(String value) {
    if (value.length == 1) return value.toLowerCase();
    var run = 1;
    while (run < value.length && _isUpper(value.codeUnitAt(run))) {
      run++;
    }
    if (run == 1) return '${value[0].toLowerCase()}${value.substring(1)}';
    if (run == value.length) return value.toLowerCase();
    final acronymEnd = run - 1;
    return '${value.substring(0, acronymEnd).toLowerCase()}${value.substring(acronymEnd)}';
  }

  bool _isUpper(int codeUnit) => codeUnit >= 65 && codeUnit <= 90;
}
