import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';
import 'package:path/path.dart' as p;

import 'emitter.dart';
import 'errors.dart';
import 'project.dart';

final class TomgenOutput {
  const TomgenOutput(this.file, this.content);

  final File file;
  final String content;
}

final class OwnershipResult {
  const OwnershipResult({
    required this.written,
    required this.unchanged,
    required this.deleted,
  });

  final int written;
  final int unchanged;
  final int deleted;
}

typedef OwnershipHook = void Function(String stage);

/// Owns and transactionally updates phase-one files generated by tomgen.
final class OwnershipStore {
  OwnershipStore(this.root, {this.hook});

  final Directory root;
  final OwnershipHook? hook;

  File get manifestFile =>
      File(p.join(root.path, '.dart_tool', 'tomgen', 'manifest.json'));

  File get _lockFile => File(p.join(root.path, '.dart_tool', 'tomgen', 'lock'));

  OwnershipResult commit(List<TomgenOutput> outputs) => _withLock(() {
    final prior = _readManifest();
    final next = <String, String>{};
    final byPath = <String, TomgenOutput>{};
    for (final output in outputs) {
      final relative = _relativeOwnedPath(output.file);
      if (byPath.containsKey(relative)) {
        throw TomgenException('Multiple targets produce "$relative".');
      }
      byPath[relative] = output;
      next[relative] = _hash(output.content);
    }

    for (final entry in prior.entries) {
      _verifyOwned(entry.key, entry.value);
    }
    for (final entry in byPath.entries) {
      final file = entry.value.file;
      if (file.existsSync() && !prior.containsKey(entry.key)) {
        final content = file.readAsStringSync();
        final adoptable =
            content.startsWith(generatedNotice) &&
            _hash(content) == next[entry.key];
        if (!adoptable) {
          throw TomgenException(
            'Refusing to overwrite unowned file "${entry.key}".',
          );
        }
      }
    }

    final changed = <String, TomgenOutput>{};
    var unchanged = 0;
    for (final entry in byPath.entries) {
      final file = entry.value.file;
      if (file.existsSync() &&
          _hash(file.readAsStringSync()) == next[entry.key]) {
        unchanged++;
      } else {
        changed[entry.key] = entry.value;
      }
    }
    final stale = prior.keys.where((path) => !next.containsKey(path)).toList();
    _commitTransaction(changed: changed, stale: stale, next: next);
    return OwnershipResult(
      written: changed.length,
      unchanged: unchanged,
      deleted: stale.length,
    );
  });

  OwnershipResult clean() => _withLock(() {
    final prior = _readManifest();
    for (final entry in prior.entries) {
      _verifyOwned(entry.key, entry.value);
    }
    _commitTransaction(
      changed: const <String, TomgenOutput>{},
      stale: prior.keys.toList(),
      next: const <String, String>{},
      removeManifest: true,
    );
    return OwnershipResult(written: 0, unchanged: 0, deleted: prior.length);
  });

  T _withLock<T>(T Function() body) {
    _lockFile.parent.createSync(recursive: true);
    final lock = _lockFile.openSync(mode: FileMode.append);
    try {
      lock.lockSync(FileLock.exclusive);
      return body();
    } finally {
      try {
        lock.unlockSync();
      } finally {
        lock.closeSync();
      }
    }
  }

  Map<String, String> _readManifest() {
    if (!manifestFile.existsSync()) return <String, String>{};
    final Object? decoded;
    try {
      decoded = jsonDecode(manifestFile.readAsStringSync());
    } on Object catch (error) {
      throw TomgenException('Failed to parse ${manifestFile.path}: $error');
    }
    if (decoded is! Map ||
        decoded['version'] != 1 ||
        decoded['files'] is! Map) {
      throw TomgenException('${manifestFile.path} has an unsupported schema.');
    }
    final rawFiles = decoded['files'] as Map;
    if (rawFiles.keys.any((key) => key is! String) ||
        rawFiles.values.any((value) => value is! String)) {
      throw TomgenException('${manifestFile.path} has invalid file records.');
    }
    return Map<String, String>.from(rawFiles);
  }

  String _relativeOwnedPath(File file) {
    final resolved = resolveContainedPath(
      root: root,
      relativePath: p.relative(file.absolute.path, from: root.path),
      description: 'generated output "${file.path}"',
      requireDescendant: true,
    );
    return p.relative(resolved, from: root.resolveSymbolicLinksSync());
  }

  void _verifyOwned(String relative, String expectedHash) {
    final path = resolveContainedPath(
      root: root,
      relativePath: relative,
      description: 'owned path "$relative"',
      requireDescendant: true,
    );
    final file = File(path);
    if (!file.existsSync()) {
      throw TomgenException(
        'Owned generated file "$relative" is missing; reconcile '
        '${p.relative(manifestFile.path, from: root.path)} first.',
      );
    }
    final content = file.readAsStringSync();
    if (!content.startsWith(generatedNotice)) {
      throw TomgenException(
        'Owned path "$relative" no longer has the tomgen generated notice.',
      );
    }
    if (_hash(content) != expectedHash) {
      throw TomgenException(
        'Owned generated file "$relative" was edited; refusing to overwrite '
        'or delete it.',
      );
    }
  }

  void _commitTransaction({
    required Map<String, TomgenOutput> changed,
    required List<String> stale,
    required Map<String, String> next,
    bool removeManifest = false,
  }) {
    final id = '${pid}_${DateTime.now().microsecondsSinceEpoch}';
    final temporary = <String, File>{};
    final backups = <String, File>{};
    File? manifestTemp;
    File? manifestBackup;
    var manifestInstalled = false;
    final installed = <String>{};
    try {
      for (final entry in changed.entries) {
        entry.value.file.parent.createSync(recursive: true);
        final temp = File('${entry.value.file.path}.tomgen.tmp.$id');
        temp.writeAsStringSync(entry.value.content, flush: true);
        temporary[entry.key] = temp;
      }
      if (!removeManifest) {
        manifestFile.parent.createSync(recursive: true);
        manifestTemp = File('${manifestFile.path}.tomgen.tmp.$id');
        manifestTemp.writeAsStringSync(_encodeManifest(next), flush: true);
      }
      hook?.call('prepared');

      final affected = <String>{...changed.keys, ...stale}.toList()..sort();
      for (final relative in affected) {
        final file = File(p.join(root.path, relative));
        if (file.existsSync()) {
          final backup = File('${file.path}.tomgen.bak.$id');
          file.renameSync(backup.path);
          backups[relative] = backup;
        }
      }
      if (manifestFile.existsSync()) {
        manifestBackup = File('${manifestFile.path}.tomgen.bak.$id');
        manifestFile.renameSync(manifestBackup.path);
      }
      hook?.call('backed-up');

      for (final entry in changed.entries) {
        temporary[entry.key]!.renameSync(entry.value.file.path);
        installed.add(entry.key);
      }
      hook?.call('outputs-installed');

      if (!removeManifest) {
        manifestTemp!.renameSync(manifestFile.path);
        manifestInstalled = true;
      }
      hook?.call('manifest-installed');

      for (final backup in backups.values) {
        if (backup.existsSync()) backup.deleteSync();
      }
      if (manifestBackup?.existsSync() ?? false) manifestBackup!.deleteSync();
    } on Object catch (error) {
      for (final relative in installed) {
        final file = changed[relative]!.file;
        if (file.existsSync()) file.deleteSync();
      }
      if (manifestFile.existsSync() &&
          (manifestBackup != null || manifestInstalled)) {
        manifestFile.deleteSync();
      }
      for (final entry in backups.entries) {
        if (entry.value.existsSync()) {
          entry.value.renameSync(p.join(root.path, entry.key));
        }
      }
      if (manifestBackup?.existsSync() ?? false) {
        manifestBackup!.renameSync(manifestFile.path);
      }
      throw TomgenException('Failed to commit generated files: $error');
    } finally {
      for (final file in temporary.values) {
        if (file.existsSync()) file.deleteSync();
      }
      if (manifestTemp?.existsSync() ?? false) manifestTemp!.deleteSync();
    }
  }

  String _encodeManifest(Map<String, String> files) {
    final ordered = <String, String>{};
    final keys = files.keys.toList()..sort();
    for (final key in keys) {
      ordered[key] = files[key]!;
    }
    return '${const JsonEncoder.withIndent('  ').convert(<String, Object>{'version': 1, 'files': ordered})}\n';
  }

  String _hash(String content) =>
      sha256.convert(utf8.encode(content)).toString();
}
